# Homework 3
Pamela Pupiales 
213871

## 1. [10 pts] Given a list of list of dimension m x n (2-D matrix) representing a map of '1's (land) and '0's (water), write a Python function that returns the number of islands and takes the matrix as input. 

- An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.\
- Assume all four edges of the matrix are all surrounded by water.
- Write an implementation for BFS and one for DFS


Example:

```
Input: map = [
  ["1","1","0","0","0"],
  ["1","1","0","0","0"],
  ["0","0","1","0","0"],
  ["0","0","0","1","1"]
]
Output: 3
```


In [87]:
#BFS
import numpy as np
class islas_:
    
    def __init__(self, gd, gd_v):
        self.gd = gd
        self.gd_v = gd_v
        
    def numIslas(self):
        fila = len(self.gd)
        col = len(self.gd[0])
        
        for i in range(fila):
            self.gd_v.append([0]*col)
    
        islas = []
        
        for f in range(fila):
            for c in range(col):
                if self.gd_v[f][c] == 0 and self.gd[f][c] == 1:
                    islas.append((f, c))
                    self.busqueda(self.gd, self.gd_v, (f, c))  
                    
        return len(islas)
        
    def busqueda(self, gd,  gv, isl: tuple):
        queue = [isl]
        fila = len(self.gd)
        col = len(self.gd[0])
        
        while len(queue) != 0:
            conf = queue.pop(0)
            m = conf[0]
            n = conf[1]
            gv[m][n] = 1
            
            if gd[m][n] == 1:
                if m-1 >= 0 and gv[m-1][n] != 1:
                    queue.append((m-1, n))
                if n-1 >= 0 and gv[m][n-1] != 1:
                    queue.append((m, n-1))
                if m+1 < fila and gv[m+1][n] != 1:
                    queue.append((m+1, n))
                if n+1 < col and gv[m][n+1] != 1:
                    queue.append((m, n+1))
                    
F = int(input("Ingrese numero de filas:"))
C = int(input("Ingrese numero de columnas:"))

print("Ingrese valores de 0 o 1 separados por el espacio: ")

entradas = list(map(int, input().split()))
matrix = np.array(entradas).reshape(F, C)
print(matrix)

gv = []
g = islas_(matrix, gv)

print("Hay", g.numIslas(), "isla(s)")    

Ingrese numero de filas:4
Ingrese numero de columnas:5
Ingrese valores de 0 o 1 separados por el espacio: 
1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1
[[1 1 0 0 0]
 [1 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]
Hay 2 isla(s)


In [77]:
#DFS
class islas:
    def __init__(self, gd, gd_v):
        self.gd = gd
        self.gd_v = gd_v

    def numIslas(self):
        fila = len(self.gd)
        col = len(self.gd[0])
        
        for i in range(fila):
            self.gd_v.append([0]*col)
    
        islas = []
        
        for f in range(fila):
            for c in range(col):
                if self.gd_v[f][c] == 0 and self.gd[f][c] == 1:
                    islas.append((f, c))
                    self.busqueda(self.gd, self.gd_v, (f, c))  
                    
        return len(islas)

    def busqueda(self, gd,  gv, isl: tuple):
        m = isl[0]
        n = isl[1]
        gv[m][n] = 1

        if gd[m][n] == 1:
            if m-1 >= 0 and gv[m-1][n] != 1:
                self.busqueda(gd, gv, (m-1, n))
            if n-1 >= 0 and gv[m][n-1] != 1:
                self.busqueda(gd, gv, (m, n-1))
            if m+1 < len(grid) and gv[m+1][n] != 1:
                self.busqueda(gd, gv, (m+1, n))
            if n+1 < len(grid[0]) and gv[m][n+1] != 1:
                self.busqueda(gd, gv, (m, n+1))

F = int(input("Ingrese numero de filas:"))
C = int(input("Ingrese numero de columnas:"))

print("Ingrese valores de 0 o 1 separados por el espacio: ")
entradas = list(map(int, input().split()))

matrix = np.array(entradas).reshape(F, C)
print(matrix)

gv = []
g = islas(matrix, gv)

print("Hay", g.numIslas(), "isla(s)")    

Ingrese numero de filas:4
Ingrese numero de columnas:5
Ingrese valores de 0 o 1 separados por el espacio: 
1 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1
[[1 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 1]]
Hay 3 isla(s)


## 2. [5 pts] A perfect square is an integer that is the square of an integer; in other words, it is the product of some integer with itself. For example, 1, 4, 9, and 16 are perfect squares, and 2 and 5 are not perfect squares

Use BFS and write a Python function that gets a number `n` as input and return the least number of perfect square numbers that sum to `n`

Example 1:

```
Input: n = 12
Output: 3
Explanation: 12 = 4 + 4 + 4.
```

Example 2:
```
Input: n = 13
Output: 2
Explanation: 13 = 4 + 9.
```


**Hint 1:**

You can build a graph (n-ary tree) using the input as the root, and the children the difference between the input and the perfect squares less or equal to the input. Each of the children can become the root of a subtree built using the same idea. For example, the graph below reflects the first level of the tree for `n=17`. 

![](./hint1.png)


Once the graph is defined, you can run BFS

In [84]:
import math
class cuadrPerfecto:
    def __init__(self, n, cuad):
        self.n = n
        self.cuad = cuad

    def Cuadrados(self):
        for i in range(1, int(math.sqrt(self.n))+1):
            self.cuad.append(i*i)
        num = [self.n]
        resp = 0
        
        while 0 not in num:
            anterior = num
            num = []
            for i in anterior:
                for j in self.cuad:
                    if i-j >= 0:
                        num.append(i-j)
            resp += 1
        return resp

n = int(input("Ingrese numero: "))
c = []
S = cuadrPerfecto(n, c)
print("Salida: ", S.Cuadrados())

Ingrese numero: 12
Salida:  3
